export interface IProducto{
 id_prod:number;
codigo_prod:string;
codbarra_prod:string;
descripcion_prod:string;
present_prod:string;
precio_prod:number;
stockmin_prod:number;
stockmax_prod:number;
stock_prod:number;
fechaing_prod:string;
fechaelab_prod:string;
fechacad_prod:string;
aplicaiva_prod:string;
aplicaice_prod:string;
util_prod:number;
comision_prod:number;
imagen_prod:string;
observ_prod:string;
estado_prod:string;
id_bod:number;
id_marca:number;
id_cat:number;
id_empresa:number;
}
